/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Circular.Array;

import org.checkerframework.checker.units.qual.C;

import java.sql.Array;
import java.util.ArrayList;
import java.util.List;

public class App {


    public static void main(String[] args) {
        CircularArray circularArray = new CircularArray(2, 3, 4, 5);

        circularArray.printArray();
        System.out.println( "The number at this point is " + circularArray.getObject(4));

        circularArray.moveRight();
        circularArray.moveRight();
        circularArray.moveLeft();

        System.out.println( "The number at this point is " + circularArray.getIndex());


    }




}
